import type { WasmModule } from "./types";

let wasmModule: WasmModule | null = null;
let initPromise: Promise<WasmModule> | null = null;

export async function initWasm(): Promise<WasmModule> {
  if (wasmModule) {
    return wasmModule;
  }

  if (initPromise) {
    return initPromise;
  }

  initPromise = (async () => {
    // Dynamic import of the inline WASM module
    // This file is generated by esbuild.config.mjs
    const wasm = await import("../../wasm/vault_tree_wasm_inline.js");
    await wasm.default();

    wasmModule = {
      parse_frontmatter: wasm.parse_frontmatter,
      parse_links: wasm.parse_links,
      normalize_link: wasm.normalize_link,
      compute_hash: wasm.compute_hash,
      build_tree: wasm.build_tree,
    };

    return wasmModule;
  })();

  return initPromise;
}

export function getWasm(): WasmModule | null {
  return wasmModule;
}
